animal = input("An animal: ")
noun = input("A noun: ")
p_verb = input("A past tense verb: ")
tool = input("A tool: ")
noun2 = input("A noun: ")

print("There was once a little " + animal +  ",")
print("He wanted to open a " + noun + ", but it was " + p_verb + ".")
print("He got a " + tool + ", to pry it open.")
print("There was a cool " + noun2 + " inside of it.")